events {}

http {
    hoplite_bootstrap /etc/hestia/app.hal;

    server {
        listen 8080;

        location = /health {
            hoplite_content hestia.origin/health;
        }

        location /inspect {
            hoplite_content hestia.origin/inspect;
        }
    }
}
