/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ac2bafafacf08c39fa5421b9866c2dbb)
interface __BaseEnv_Env {
	ALLOWED_ORIGINS: "https://hestia-demo.greenways.ai,http://localhost:8787,http://127.0.0.1:8787";
	STUN_URLS: "stun:stun.cloudflare.com:3478";
	MAX_MESSAGE_BYTES: "65536";
	CEREMONY_ROOMS: DurableObjectNamespace<import("./src/index").CeremonyRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CeremonyRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "STUN_URLS" | "MAX_MESSAGE_BYTES">> {}
}
